/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.hesol.exp1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class UnitConverterTest {
    @Test
    public void testInchesToFeetConversion() {
        double result = UnitConverter.convert(12, "in", "ft");
        assertEquals(1, result, 0.001);
    }

    @Test
    public void testMilesToMetersConversion() {
        double result = UnitConverter.convert(1, "mi", "m");
        assertEquals(1609.344, result, 0.001);
    }

    @Test
    public void testInvalidUnitConversion() {
        double result = UnitConverter.convert(10, "invalid", "m");
        assertTrue(Double.isNaN(result));
    }

    // Add more test cases for other conversions as needed
}

